In [2]:
import numpy as np

In [6]:
numbers = np.array([2,3,5,7,11])
type(numbers)


numpy.ndarray

In [8]:
numbers

array([ 2,  3,  5,  7, 11])

In [10]:
np.array([[2,4,6,8,10], [1,3,5,7,9]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [12]:
integers = np.array([[1,3,5], [4,5,6]])
integers

array([[1, 3, 5],
       [4, 5, 6]])

In [14]:
floats = np.array ([0.1, 0.2, 0.3])
floats

array([0.1, 0.2, 0.3])

In [16]:
integers.dtype ## byte utilizzati come memoria

dtype('int64')

In [18]:
integers.ndim ##dice numero di righe che sono state utilizzate

2

In [20]:
floats.shape ## info sulla lunghezza dell'array

(3,)

In [22]:
integers.size ## sono gli elementi totali

6

In [24]:
integers.itemsize ## lunghezza array in byte

8

In [28]:
for row in integers:
    for column in row:
        print(column, end= " ")
    print()

1 3 5 
4 5 6 


In [32]:
for i in integers.flat:
    print(i, end= " ") ## serve per appiattire a una sola dimensione

1 3 5 4 5 6 

In [38]:
a = np.array([[2,4,6,8,10], [1,3,5,7,9]])
a.ndim

2

In [40]:
a.shape

(2, 5)

In [42]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [44]:
np.ones((2,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [46]:
np.full((3,5), 13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [48]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [50]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [52]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [60]:
np.arange(1, 21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [66]:
np.arange(2, 41, 2).reshape((4,5))

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [68]:
import random

In [73]:
%timeit rolls_list = [random.randrange(1,10) for i in range(0, 6_000_000)]

1.19 s ± 7.75 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [78]:
import pandas as pd

In [80]:
grades = pd.Series([87,100,30])

In [82]:
grades

0     87
1    100
2     30
dtype: int64